-- Create schema for Fetch Analytics Data Warehouse

-- Create enum for receipt status
CREATE TYPE receipt_status AS ENUM (
    'FINISHED', 'SUBMITTED', 'REJECTED', 'PENDING', 'FLAGGED'
);

-- Receipts table
CREATE TABLE receipts (
    receipt_id text PRIMARY KEY,
    user_id text NOT NULL,
    rewards_receipt_status receipt_status,
    total_spent float8,
    points_earned float8,
    bonus_points_earned int,
    bonus_points_reason text,
    purchase_date timestamptz,
    create_date timestamptz,
    date_scanned timestamptz,
    finished_date timestamptz,
    modify_date timestamptz,
    points_awarded_date timestamptz,
    purchased_item_count int
);

-- Receipt Items table
CREATE TABLE receipt_items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id text NOT NULL REFERENCES receipts(receipt_id),
    barcode text,
    description text,
    final_price float8,
    item_price float8,
    discounted_item_price float8,
    needs_fetch_review boolean DEFAULT false,
    needs_fetch_review_reason text,
    partner_item_id text,
    prevent_target_gap_points boolean DEFAULT false,
    quantity_purchased int,
    rewards_group text,
    rewards_product_partner_id text,
    brand_code text,
    competitor_rewards_group text,
    original_receipt_item_text text,
    points_earned float8,
    target_price float8,
    competitive_product boolean DEFAULT false
);

-- Enable RLS after tables are created
ALTER TABLE receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE receipt_items ENABLE ROW LEVEL SECURITY;

-- Create policies after RLS is enabled
CREATE POLICY "Enable read access for all users" ON receipts
    FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON receipt_items
    FOR SELECT USING (true); 